### PR TITLE
lindeberg2022full-ontorights updated

### PR DESCRIPTION
**Pull request by pedropaulofb**
OntoRights was updated from version 1.0 to version 1.1.

### CODE REVIEW

**Review by tgoprince — CHANGES_REQUESTED** [review]
The same comments from PR #289 apply here as well.

**Comment by pedropaulofb** [comment]
> The same comments from PR #289 apply here as well.

I already fixed the broken URL. Regarding the modification date, please check my [comment on PR 289](https://github.com/OntoUML/ontouml-models/pull/289).

**Comment by tgoprince** [comment]
Please resolve the conflicts so we can merge this PR.

**Comment by pedropaulofb** [comment]
> Please resolve the conflicts so we can merge this PR.

Fix done! PR Squashed and merged.

**Pull request merged**
