### PR TITLE
Adds image compression action on pull requests

### LINKED ISSUE #11: Github action to image size
We should configure [this](https://github.com/calibreapp/image-actions) Github action to reduce the size of images pushed to the repository automatically.

This will reduce the  manual work we have to do and the time to review PRs.

### PR DESCRIPTION
**Pull request by claudenirmf**
Adds image compression action. This action is to be triggered on pull requests.

NOTICE: there is a discussion on this action's repo about it not working in pull requests coming from forked repos (see [this issue](https://github.com/calibreapp/image-actions/issues/53) discussion). The developers have disabled the action in these cases, which may require an additional PR on the original repo to trigger the action and actually compress the image files. The disabling of the action avoids silent error on the action's log.

I have submitted a question to the developers for more clarification, but we could merge this PR in the meantime.

Closes #11.

### CODE REVIEW

**Comment by claudenirmf** [comment]
Considering [this instructions](https://github.com/calibreapp/image-actions#process-pull-requests-from-forked-repositories), I would consider having some `staging` or `development` branch from which we merge changes into master. Having a separated `master` branch should allow us running the action internally and may make it easier for us to version the repository through releases.

I would not consider creating a GitHub token with elevated permissions because this may introduce unnecessary vulnerabilities, e.g., from dependabot-like PRs.

**Comment by tgoprince** [comment]
I support your `staging` branch solution.

Could you just clarify how often do you envision merging the `staging` branch with the `master` branch?
I don't see a need to version this dataset, so I'm assuming it would follow every PR from a forked repository.

**Comment by tgoprince** [comment]
I tested this on action on #15.

It provides some nice feedback on the PR and it parses all images in the repository, but only commits those that have actually been compressed.

Overall, this is a very good script for our dataset.

Good job @claudenirmf!

**Comment by claudenirmf** [comment]
Maybe we won't need to "version" the repo, but creating releases may be necessary to ease the reproducibility of published experiments. Zenodo could also be used here. 

For the `staging` branch, I would expect a new PR from it into the `master` for every PR coming from a forked repo. I like your idea of automating this staging/pr step but I don't know if we could have problems if two PRs were to be created in a very short period of time. The second automated PR could interfere with the first, I don't know. 

I will try to add the action you suggested before merging this PR. Thanks for the feedback!

**Pull request closed without merging**
